// <auto-generated />
using System;
using Apex.Invest.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apex.Invest.Migrations.Migrations
{
    [DbContext(typeof(EntitiesDbContext))]
    [Migration("20260831141047_BondTables")]
    partial class BondTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond.BondOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BondId")
                        .HasColumnType("int")
                        .HasColumnName("BondId");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("Count");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Date");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("Price");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("BondId");

                    b.ToTable("BondOperation", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinanceInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Issuer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("PlatformId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("Ticker");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("FinanceInstrument", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinancePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FinancePlatform", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Аигенис"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Беларус Банк"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Альфа Банк"
                        });
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond.Bond", b =>
                {
                    b.HasBaseType("Apex.Invest.Domain.Entities.FinanceInstrument");

                    b.Property<decimal>("CouponRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("CouponRate");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("Currency");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("MaturityDate");

                    b.Property<int>("NextCouponDate")
                        .HasColumnType("integer")
                        .HasColumnName("NextCouponDate");

                    b.Property<decimal>("ParPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ParPrice");

                    b.Property<int>("PaymentFrequence")
                        .HasColumnType("integer")
                        .HasColumnName("PaymentFrequence");

                    b.ToTable("Bond", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond.BondOperation", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.Bond.Bond", "Bond")
                        .WithMany("Operations")
                        .HasForeignKey("BondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bond");
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinanceInstrument", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinancePlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond.Bond", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinanceInstrument", null)
                        .WithOne()
                        .HasForeignKey("Apex.Invest.Domain.Entities.Bond.Bond", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond.Bond", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
