// <auto-generated />
using System;
using Apex.Invest.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apex.Invest.Migrations.Migrations
{
    [DbContext(typeof(EntitiesDbContext))]
    [Migration("20260707041210_02_AddFinancePlatforms")]
    partial class _02_AddFinancePlatforms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apex.Invest.Domain.Entities.DepositOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Date");

                    b.Property<int>("DepositId")
                        .HasColumnType("int")
                        .HasColumnName("DepositId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id")
                        .HasName("PK_DepositOperation");

                    b.HasIndex("DepositId");

                    b.ToTable("DepositOperation", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinanceInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Issuer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("PlatformId");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PurchaseDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("Ticker");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("FinanceInstrument", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinancePlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FinancePlatform", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond", b =>
                {
                    b.HasBaseType("Apex.Invest.Domain.Entities.FinanceInstrument");

                    b.Property<decimal>("BrokerCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("BrokerCommission");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("Currency");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FirstPaymentDate");

                    b.Property<int>("Frequence")
                        .HasColumnType("int")
                        .HasColumnName("Frequence");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("InterestRate");

                    b.Property<decimal>("MarketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("MarketPrice");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MaturityDate");

                    b.Property<decimal>("NominalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("NominalPrice");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SaleDate");

                    b.ToTable("Bond", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Deposit", b =>
                {
                    b.HasBaseType("Apex.Invest.Domain.Entities.FinanceInstrument");

                    b.Property<bool>("Capitalization")
                        .HasColumnType("boolean")
                        .HasColumnName("Capitalization");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FirstPaymentDate");

                    b.Property<int>("Frequence")
                        .HasColumnType("int")
                        .HasColumnName("Frequence");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("InterestRate");

                    b.Property<bool>("IsReplenishable")
                        .HasColumnType("boolean")
                        .HasColumnName("IsReplenishable");

                    b.Property<bool>("IsTaxFree")
                        .HasColumnType("boolean")
                        .HasColumnName("IsTaxFree");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MaturityDate");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SaleDate");

                    b.ToTable("Deposit", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Share", b =>
                {
                    b.HasBaseType("Apex.Invest.Domain.Entities.FinanceInstrument");

                    b.Property<decimal>("BrokerCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("BrokerCommission");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("Currency");

                    b.Property<decimal>("DividendRate")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("DividendRate");

                    b.Property<decimal>("MarketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("MarketPrice");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.ToTable("Share", (string)null);
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.DepositOperation", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.Deposit", "Deposit")
                        .WithMany("Operations")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.FinanceInstrument", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinancePlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Bond", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinanceInstrument", null)
                        .WithOne()
                        .HasForeignKey("Apex.Invest.Domain.Entities.Bond", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinanceInstrument", null)
                        .WithOne()
                        .HasForeignKey("Apex.Invest.Domain.Entities.Deposit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Share", b =>
                {
                    b.HasOne("Apex.Invest.Domain.Entities.FinanceInstrument", null)
                        .WithOne()
                        .HasForeignKey("Apex.Invest.Domain.Entities.Share", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Invest.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
